### ISSUE TITLE
No module named 'extinction_plot'

### ISSUE THREAD

**Issue by brettlv** [kbarbary/extinction#12]
error happens when 

import extinction

No module named 'extinction_plot'

**Comment by kbarbary** [comment]
Can you paste the full traceback (in triple backticks: ` ``` `)? What directory were you in when you ran `import extinction`?

**Comment by brettlv** [comment]
> Can you paste the full traceback (in triple backticks: `` ``` ``)? What directory were you in when you ran `import extinction`?

sorry I get it . no problem now.

maybe extinction_plot is not included in extinction

**Comment by kbarbary** [comment]
There's an [`extinction_plot` module](https://github.com/kbarbary/extinction/blob/master/docs/extinction_plot.py) in the docs directory, but it is just a helper for generating the documentation. It isn't distributed with extinction itself.
