### ISSUE TITLE
Python 3.10 / MacOS wheel build failure

### ISSUE THREAD

**Issue by kbarbary** [kbarbary/extinction#24]
In the v0.4.6 release, all wheels build successfully except for the MacOS wheel on CPython 3.10, which failed with [this error](https://github.com/kbarbary/extinction/runs/3510747205?check_suite_focus=true#step:4:535).

@kboone any ideas?

**Comment by kboone** [comment]
Yes. cibuildwheel recently added support for Python 3.10 (which isn't released yet). The latest release of numpy works on Python 3.10 with windows/linux, but isn't compatible on mac yet for some reason. This package depends on numpy which causes that build to fail.

I'm not sure what the best way to handle this is. I enabled a "continue on failure" option in the Actions script that will show you which builds failed, but upload the rest. That's what happened here. Another option would be to pin to version 2.0.1 of cibuildwheel that doesn't do Python 3.10 builds and wait for numpy to release a mac wheel before unpinning.

**Comment by kbarbary** [comment]
Cool, thanks for the overview! Since 3.10 isn't released yet, having wheels for it is a nice bonus but shouldn't be expected. So I think it's fine to ignore this for now.

**Comment by jeremykubica** [comment]
Is it possible to generate wheels for the 3.10+ now. Seeing the following error (via sncosmo) in my builds:

```
/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/sncosmo/__init__.py:147: in <module>
    from .models import *
/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/sncosmo/models.py:11: in <module>
    import extinction
extinction.pyx:1: in init extinction
    ???
E   ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```
