### ISSUE TITLE
Create release for Zenodo?

### ISSUE THREAD

**Issue by jradavenport** [kbarbary/extinction#5]
Thanks for creating this helpful Python package, so that I don't have to go code up all those equations!! This code is very helpful in a [project](https://github.com/jradavenport/GALEX_Boyajian/) I am working on, and I would like to be able to cite it.

Would you consider making a release to Zenodo to get a DOI, so that it could be easily cited in a paper?

**Comment by kbarbary** [comment]
Thanks! I'll try to do that.

**Comment by kbarbary** [comment]
Done! https://zenodo.org/record/804967

**Comment by jradavenport** [comment]
Awesome!!! Thank you 👍
